---
- name: Install AD-Domain-Services feature
  win_feature:
    name=AD-Domain-Services
    include_management_tools=yes
    include_sub_features=yes
    state=present


- name: Win Domain registration
  win_domain:
    dns_domain_name: ad1.6e7a.example.opentlc.com
    safe_mode_password: jVMijRwLbI02gFCo2xkjlZ9lxEA7bm7zgg==
  register: domain_state

- name: Windows reboot
  win_reboot:
    when: domain_state.reboot_required

#- name: Print out the domain name list
#  shell: nltest /dclist:{{ ad1.6e7a.example.opentlc.com }}")